export default {
  version: 1,
  themeName: 'walden',
  theme: {
    seriesCnt: '6',
    backgroundColor: 'rgba(0,0,0,0)',
    titleColor: '#1f2937',
    subtitleColor: '#9ca3af',
    textColorShow: false,
    textColor: '#6b7280',
    markTextColor: '#ffffff',
    color: ['#45d3f5', '#ffba69', '#65789b', '#8676ff', '#3ee097', '#5792ff'],
    borderColor: '#e5e7eb',
    borderWidth: '0',
    visualMapColor: ['#2a99c9', '#afe8ff'],
    legendTextColor: '#6b7280',
    kColor: '#e6a0d2',
    kColor0: 'transparent',
    kBorderColor: '#e6a0d2',
    kBorderColor0: '#3fb1e3',
    kBorderWidth: '2',
    lineWidth: '3',
    symbolSize: '8',
    symbol: 'emptyCircle',
    symbolBorderWidth: '2',
    lineSmooth: false,
    graphLineWidth: '1',
    graphLineColor: '#e5e7eb',
    mapLabelColor: '#ffffff',
    mapLabelColorE: '#3fb1e3',
    mapBorderColor: '#aaaaaa',
    mapBorderColorE: '#3fb1e3',
    mapBorderWidth: 0.5,
    mapBorderWidthE: 1,
    mapAreaColor: '#eeeeee',
    mapAreaColorE: 'rgba(63,177,227,0.25)',
    axes: [
      {
        type: 'all',
        name: '通用坐标轴',
        axisLineShow: true,
        axisLineColor: '#6b7280',
        axisTickShow: false,
        axisTickColor: '#6b7280',
        axisLabelShow: true,
        axisLabelColor: '#6b7280',
        splitLineShow: true,
        splitLineColor: ['#e5e7eb'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.05)', 'rgba(200,200,200,0.02)'],
      },
      {
        type: 'category',
        name: '类目坐标轴',
        axisLineShow: true,
        axisLineColor: '#6b7280',
        axisTickShow: true,
        axisTickColor: '#6b7280',
        axisLabelShow: true,
        axisLabelColor: '#6b7280',
        splitLineShow: false,
        splitLineColor: ['#e5e7eb'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.05)', 'rgba(200,200,200,0.02)'],
      },
      {
        type: 'value',
        name: '数值坐标轴',
        axisLineShow: true,
        axisLineColor: '#6b7280',
        axisTickShow: true,
        axisTickColor: '#6b7280',
        axisLabelShow: true,
        axisLabelColor: '#6b7280',
        splitLineShow: true,
        splitLineColor: ['#e5e7eb'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.05)', 'rgba(200,200,200,0.02)'],
      },
      {
        type: 'log',
        name: '对数坐标轴',
        axisLineShow: true,
        axisLineColor: '#6b7280',
        axisTickShow: true,
        axisTickColor: '#6b7280',
        axisLabelShow: true,
        axisLabelColor: '#6b7280',
        splitLineShow: true,
        splitLineColor: ['#e5e7eb'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.05)', 'rgba(200,200,200,0.02)'],
      },
      {
        type: 'time',
        name: '时间坐标轴',
        axisLineShow: true,
        axisLineColor: '#333',
        axisTickShow: true,
        axisTickColor: '#333',
        axisLabelShow: true,
        axisLabelColor: '#333',
        splitLineShow: true,
        splitLineColor: ['#ccc'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.05)', 'rgba(200,200,200,0.02)'],
      },
    ],
    axisSeperateSetting: false,
    toolboxColor: '#9ca3af',
    toolboxEmphasisColor: '#6b7280',
    tooltipAxisColor: '#e5e7eb',
    tooltipAxisWidth: '1',
    timelineLineColor: '#626c91',
    timelineLineWidth: 1,
    timelineItemColor: '#626c91',
    timelineItemColorE: '#626c91',
    timelineCheckColor: '#3fb1e3',
    timelineCheckBorderColor: '#3fb1e3',
    timelineItemBorderWidth: 1,
    timelineControlColor: '#626c91',
    timelineControlBorderColor: '#626c91',
    timelineControlBorderWidth: 0.5,
    timelineLabelColor: '#626c91',
    datazoomBackgroundColor: 'rgba(255,255,255,0)',
    datazoomDataColor: 'rgba(222,222,222,1)',
    datazoomFillColor: 'rgba(114,230,212,0.25)',
    datazoomHandleColor: '#cccccc',
    datazoomHandleWidth: '100',
    datazoomLabelColor: '#999999',
  },
}
